### ISSUE TITLE
Fix browser support message

### ISSUE THREAD

**Issue by ZorinFoss** [Comp-Labs/Google-Docs#34]
Hi @complabs28,

I got this message everytime i open google document.

**Screenshot**
![Screenshot_20230920_132650](https://github.com/Comp-Labs/Google-Docs/assets/132728893/b3452137-3e1d-4643-a238-19b83634455a)

Thanks,

**Comment by RudraSen2** [comment]
Sorry for the late response. I have to upgrade the Firefox browser version in the user agent. Please wait until this issue is fixed. Thanks for reporting!

**Comment by ZorinFoss** [comment]
Thanks
