### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Bllacky** [Comp-Labs/Google-Docs#49]
Hi!
When are you planning a new release? I keep getting a Firefox version error on Windows.
Thanks

**Comment by RudraSen2** [comment]
I am a student so I don't have time and am also finding a solution for this as I cannot find one. I will fix this as soon as I can Thanks.

**Comment by RudraSen2** [comment]
@Bllacky no problem, I'll fix it ASAP. I completely forgot that it was pending.

**Comment by Bllacky** [comment]
If you can release a new build, that would be amazing. I have to say your project is really helpful since I can easily get into Google Sheets and everything runs sandboxed.

**Comment by Bllacky** [comment]
Do you know how I can build your project?

**Comment by RudraSen2** [comment]
No, I don't think so I know it. So, are you trying to say that you will help?

**Comment by Bllacky** [comment]
I see the last release was in November 2022. How did you build it then ?
